import type { Metadata } from "next";
import "./globals.scss";
// import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <div className="header">
          <div className="container">
            <Link href="/" className="btn">
              測試
            </Link>
          </div>
        </div> */}

        {children}
      </body>
    </html>
  );
}
