export const dataKaomoji = {
  高興: {
    categoryTags: ["高興"],
    items: [
      { symbol: "(ﾟ∀ﾟ)", tags: [""] },
      { symbol: "(*ﾟ∀ﾟ*)", tags: [""] },
      { symbol: "(*´▽`*)", tags: [""] },
      { symbol: "ヽ(●´∀`●)ﾉ", tags: [""] },
      { symbol: "(*´艸`*)", tags: [""] },
      { symbol: "(*‘ v`*)", tags: [""] },
      { symbol: "(^u^)", tags: [""] },
      { symbol: "(^y^)", tags: [""] },
      { symbol: "(ﾉ>ω<)ﾉ", tags: [""] },
      { symbol: "(｡A｡)", tags: [""] },
      { symbol: "(ﾉ∀`*)", tags: [""] },
      { symbol: "(*’ｰ’*)", tags: [""] },
      { symbol: "d(`･∀･)b", tags: [""] },
      { symbol: "(,,・ω・,,)", tags: [""] },
      { symbol: "(((ﾟдﾟ)))", tags: [""] },
      { symbol: "(｡◕∀◕｡)", tags: [""] },
      { symbol: "ヽ(✿ﾟ▽ﾟ)ノ", tags: [""] },
      { symbol: "(」・ω・)」うー！(／・ω・)／にゃー！", tags: [""] },
      { symbol: "｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡", tags: [""] },
      { symbol: "ξ( ✿＞◡❛)▄︻▇▇〓▄︻┻┳═一", tags: [""] },
      { symbol: "(✪ω✪)", tags: [""] },
      { symbol: "(⁰▿⁰)", tags: [""] },
      { symbol: "(๑´ㅂ`๑)", tags: [""] },
      { symbol: "ヽ(・×・´)ゞ", tags: [""] },
      { symbol: "(o´罒`o)", tags: [""] },
      { symbol: "☆⌒(*^-゜)v", tags: [""] },
      { symbol: "(灬ºωº灬)", tags: [""] },
      { symbol: "(´///☁///`)", tags: [""] },
      { symbol: "(❛◡❛✿)", tags: [""] },
      { symbol: "(๑• . •๑)", tags: [""] },
      { symbol: "(ㅅ˘ㅂ˘)", tags: [""] },
      { symbol: "٩(｡・ω・｡)﻿و", tags: [""] },
      { symbol: "(*ˇωˇ*人)", tags: [""] },
      { symbol: "☆^(ｏ´Ф∇Ф)o", tags: [""] },
      { symbol: "(,,ﾟДﾟ)", tags: [""] },
      { symbol: "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧", tags: [""] },
      { symbol: "o(☆Ф∇Ф☆)o", tags: [""] },
      { symbol: "( • ̀ω•́ )", tags: [""] },
      { symbol: "(ﾟω´)", tags: [""] },
      { symbol: "(●｀ 艸 ´)", tags: [""] },
      { symbol: "ヽ(㊤V㊤*)ﾉ", tags: [""] },
      { symbol: "＼(●´ϖ`●)／", tags: [""] },
      { symbol: "(•ㅂ•)/", tags: [""] },
      { symbol: "( *´◒`*)", tags: [""] },
      { symbol: "(((o(*ﾟ▽ﾟ*)o)))", tags: [""] },
      { symbol: "٩(๑•̀ω•́๑)۶", tags: [""] },
      { symbol: "(＊゜ー゜)b", tags: [""] },
      { symbol: "(๑¯∀¯๑)", tags: [""] },
      { symbol: "ヽ(●´ε｀●)ノ", tags: [""] },
      { symbol: "ヽ( ° ▽°)ノ", tags: [""] },
      { symbol: "(ゝ∀･)⌒☆", tags: [""] },
      { symbol: "(╯°▽°)╯ ┻━┻", tags: [""] },
      { symbol: "(｡・ω・｡)", tags: [""] },
      { symbol: "(•‾⌣‾•)", tags: [""] },
      { symbol: "✧*｡٩(ˊᗜˋ*)و✧*｡", tags: [""] },
      { symbol: "⁽⁽ ◟(∗ ˊωˋ ∗)◞ ⁾⁾", tags: [""] },
      { symbol: "＼＼\\٩( 'ω' )و //／／", tags: [""] },
      { symbol: "（๑ • ‿ • ๑ ）", tags: [""] },
      { symbol: "ヽ( ^ω^ ゞ )", tags: [""] },
      { symbol: "(๑ ^ ₃•๑)", tags: [""] },
      { symbol: "⁽⁽٩(๑˃̶͈̀ ᗨ ˂̶͈́)۶⁾⁾", tags: [""] },
      { symbol: "੭ ˙ᗜ˙ )੭", tags: [""] },
      { symbol: ">ヮ<", tags: [""] },
      { symbol: "ᴖ ᴈ ᴖ", tags: [""] },
    ],
  },
  憤怒: {
    categoryTags: ["憤怒", "生氣"],
    items: [
      { symbol: "(`3´)", tags: [""] },
      { symbol: "(ﾟ皿ﾟﾒ)", tags: [""] },
      { symbol: "(ﾒ ﾟ皿ﾟ)ﾒ", tags: [""] },
      { symbol: "(┛`д´)┛", tags: [""] },
      { symbol: "(#`Д´)ﾉ", tags: [""] },
      { symbol: "(#`皿´)", tags: [""] },
      { symbol: "(-`ェ´-╬)", tags: [""] },
      { symbol: "(╬ﾟдﾟ)", tags: [""] },
      { symbol: "(`д´)", tags: [""] },
      { symbol: "ヽ(#`Д´)ﾉ", tags: [""] },
      { symbol: "(╬☉д⊙)", tags: [""] },
      { symbol: "(／‵Д′)／~ ╧╧", tags: [""] },
      { symbol: "(　◞≼☸≽◟ ._ゝ◞≼☸≽◟)", tags: [""] },
      { symbol: "⊙谷⊙", tags: [""] },
      { symbol: "ヽ(`Д´)ノ", tags: [""] },
      { symbol: "(╬ﾟдﾟ)▄︻┻┳═一", tags: [""] },
      { symbol: "٩(ŏ﹏ŏ、)۶", tags: [""] },
      { symbol: "（ ´ﾟ,_」ﾟ）ﾊﾞｶｼﾞｬﾈｰﾉ", tags: [""] },
      { symbol: "(╬ﾟ ◣ ﾟ)", tags: [""] },
      { symbol: "(☄◣ω◢)☄", tags: [""] },
      { symbol: "(ಠ益ಠ)", tags: [""] },
      { symbol: "(ﾒﾟДﾟ)ﾒ", tags: [""] },
      { symbol: "(`へ´≠)", tags: [""] },
      { symbol: "(・`ω´・)", tags: [""] },
      { symbol: "(#ﾟ⊿`)凸", tags: [""] },
      { symbol: "╯-____-)╯~═╩════╩═", tags: [""] },
      { symbol: "(*≥▽≤)ツ┏━┓", tags: [""] },
      { symbol: "( ╯' - ')╯ ┻━┻", tags: [""] },
      { symbol: "(╯°O°)╯┻━┻", tags: [""] },
      { symbol: "(╯°Д°)╯ ┻━┻", tags: [""] },
      { symbol: "(๑•ૅω•´๑)", tags: [""] },
      { symbol: "(╯ŏ益ŏ)╯︵(ヽo□o)ヽ", tags: [""] },
      { symbol: "(╬▼дﾟ)▄︻┻┳═一", tags: [""] },
      { symbol: "(╯•̀ὤ•́)╯", tags: [""] },
      { symbol: "(； ･`д･´)", tags: [""] },
      { symbol: "ᕕ༼ ͠ຈ Ĺ̯ ͠ຈ ༽┌∩┐", tags: [""] },
      { symbol: "(╬ﾟдﾟ)╭∩╮", tags: [""] },
      { symbol: "٩(◦`꒳´◦)۶", tags: [""] },
      { symbol: "(ノ▼Д▼)ノ", tags: [""] },
      { symbol: "(ꐦ°᷄д°᷅)", tags: [""] },
    ],
  },
  哀愁: {
    categoryTags: ["哀愁", "悲劇"],
    items: [
      { symbol: "(〒︿〒)", tags: [""] },
      { symbol: "｡ﾟヽ(ﾟ´Д`)ﾉﾟ｡", tags: [""] },
      { symbol: "(´ﾟдﾟ`)", tags: [""] },
      { symbol: "(๑•́ ₃ •̀๑)", tags: [""] },
      { symbol: "இдஇ", tags: [""] },
      { symbol: "(´;ω;`)", tags: [""] },
      { symbol: "( ˘･з･)", tags: [""] },
      { symbol: "(´Ａ｀。)", tags: [""] },
      { symbol: "(╥﹏╥)", tags: [""] },
      { symbol: "(◜◔。◔◝)", tags: [""] },
      { symbol: "(　´・◡・｀)", tags: [""] },
      { symbol: "(☍﹏⁰)", tags: [""] },
      { symbol: "ヾ(◎´・ω・｀)ノ", tags: [""] },
      { symbol: "( ´•̥̥̥ω•̥̥̥` )", tags: [""] },
      { symbol: "( •́ὤ•̀)", tags: [""] },
      { symbol: "( ´•̥×•̥` )", tags: [""] },
      { symbol: "(☍﹏⁰。)", tags: [""] },
      { symbol: "L(　；ω；)┘三└(；ω；　)」", tags: [""] },
      { symbol: "༼ ༎ຶ ෴ ༎ຶ༽", tags: [""] },
      { symbol: "ヾ(;ﾟ;Д;ﾟ;)ﾉﾞ", tags: [""] },
      { symbol: "。･ﾟ･(つд`ﾟ)･ﾟ･", tags: [""] },
      { symbol: "⊂彡☆))д`)", tags: [""] },
      { symbol: "・゜・(PД`q｡)・゜・", tags: [""] },
      { symbol: "⋉(● ∸ ●)⋊", tags: [""] },
      { symbol: "Σ(ﾟДﾟ；≡；ﾟдﾟ)", tags: [""] },
      { symbol: "╰(〒皿〒)╯", tags: [""] },
      { symbol: "(◓Д◒)✄╰⋃╯", tags: [""] },
      { symbol: "(°ཀ°)", tags: [""] },
      { symbol: "( º﹃º )", tags: [""] },
      { symbol: "(›´ω`‹ )", tags: [""] },
      { symbol: "( ×ω× )", tags: [""] },
      { symbol: "(✺ω✺)", tags: [""] },
      { symbol: "(ﾟ々｡)", tags: [""] },
      { symbol: "_(┐「﹃ﾟ｡)_", tags: [""] },
      { symbol: "_(´ཀ`」 ∠)_", tags: [""] },
      { symbol: "0(:3　)～ ('､3_ヽ)_", tags: [""] },
      { symbol: ":;(∩´﹏`∩);:", tags: [""] },
      { symbol: "ΩДΩ", tags: [""] },
      { symbol: "( ͡ʘ ͜ʖ ͡ʘ)", tags: [""] },
      { symbol: "_(┐ ◟;ﾟдﾟ)ノ", tags: [""] },
    ],
  },

  愉悅: {
    categoryTags: ["愉悅"],
    items: [
      { symbol: "(ﾟд⊙)", tags: [""] },
      { symbol: "(ゝ∀･)b", tags: [""] },
      { symbol: "d(d＇∀＇)", tags: [""] },
      { symbol: "(ﾟ3ﾟ)～♪", tags: [""] },
      { symbol: "(〃∀〃)", tags: [""] },
      { symbol: "(శωశ)", tags: [""] },
      { symbol: "(◔౪◔)", tags: [""] },
      { symbol: "☝( ◠‿◠ )☝", tags: [""] },
      { symbol: "((└(:3」┌)┘))", tags: [""] },
      { symbol: "(∂ω∂)", tags: [""] },
      { symbol: "(<ゝω・)☆", tags: [""] },
      { symbol: "( • ̀ω•́  )✧", tags: [""] },
      { symbol: "_(:3 ⌒ﾞ)_", tags: [""] },
      { symbol: "( σ՞ਊ ՞)σ", tags: [""] },
      { symbol: "ლ(́◕◞౪◟◕‵ლ)", tags: [""] },
      { symbol: "(◕ܫ◕)", tags: [""] },
      { symbol: "(´ΘωΘ`)", tags: [""] },
      { symbol: "_(¦3」∠)_", tags: [""] },
      { symbol: "♥(´∀` )人", tags: [""] },
      { symbol: "( ～'ω')～", tags: [""] },
      { symbol: "(๑ơ ₃ ơ)♥", tags: [""] },
      { symbol: "(^ρ^)/", tags: [""] },
      { symbol: "(๑´ㅁ`)", tags: [""] },
      { symbol: "( ﾒ∀・)", tags: [""] },
      { symbol: "。゜+.(人-ω◕)゜+.゜", tags: [""] },
      { symbol: "━(ﾟ∀ﾟ)━( ﾟ∀)━( ﾟ)━( )━( )━(ﾟ)━(∀ﾟ)━(ﾟ∀ﾟ)━", tags: [""] },
      { symbol: "(￫ܫ￩)", tags: [""] },
      { symbol: "(♛‿♛)", tags: [""] },
      { symbol: "(́提◞౪◟供‵)", tags: [""] },
      { symbol: "✧◝(⁰▿⁰)◜✧", tags: [""] },
      { symbol: "(・ε・)", tags: [""] },
      { symbol: "(꒪ͦᴗ̵̍꒪ͦ )", tags: [""] },
      { symbol: "(*ﾟーﾟ)", tags: [""] },
      { symbol: "◝(　ﾟ∀ ﾟ )◟", tags: [""] },
      { symbol: "(*´д`)", tags: [""] },
      { symbol: "(❁´ω`❁)*✲ﾟ*", tags: [""] },
      { symbol: "╰(〞︶〝) ╯", tags: [""] },
      { symbol: "(▰˘◡˘▰)", tags: [""] },
      { symbol: "(っ●ω●)っ", tags: [""] },
      { symbol: "(●⁰౪⁰●)", tags: [""] },
      { symbol: "....ˊˋ------｡:.ﾟ_ヽ(_´∀`_)ﾉ_.:｡((浮水", tags: [""] },
      { symbol: "ᕕ ( ᐛ ) ᕗ", tags: [""] },
      { symbol: "ε(*´･∀･｀)зﾞ", tags: [""] },
      { symbol: "(́순◞౪◟순‵)", tags: [""] },
      { symbol: "(//´/◒/`//)", tags: [""] },
      { symbol: "(づ′▽`)づ", tags: [""] },
      { symbol: "(◍•ᴗ•◍)ゝ", tags: [""] },
      { symbol: "( ´థ౪థ）σ", tags: [""] },
      { symbol: "(☞ﾟ∀ﾟ)ﾟ∀ﾟ)☞", tags: [""] },
      { symbol: "(⁄ ⁄>⁄ω⁄<⁄ ⁄)⁄", tags: [""] },
      { symbol: "(੭ु´ ᐜ `)੭ु⁾⁾", tags: [""] },
      { symbol: "*ଘ(੭*ˊᵕˋ)੭* ੈ✩‧₊˚", tags: [""] },
      { symbol: "₍₍◝(･'ω'･)◟⁾⁾", tags: [""] },
      { symbol: "ヾ(´︶`*)ﾉ♬", tags: [""] },
      { symbol: "(✧≖‿ゝ≖)", tags: [""] },
      { symbol: "(σﾟ∀ﾟ)σ..:*☆", tags: [""] },
      { symbol: "(❀╹◡╹)", tags: [""] },
      { symbol: "(⁎⁍̴̛ᴗ⁍̴̛⁎)‼", tags: [""] },
      { symbol: "< (￣︶￣)>", tags: [""] },
      { symbol: "⁽⁽ଘ( ˙꒳˙ )ଓ⁾⁾", tags: [""] },
      { symbol: "(╯⊙ ⊱ ⊙╰ )", tags: [""] },
      { symbol: "(´◓ｑ◔｀)", tags: [""] },
      { symbol: "巴麻美 ξ（ ✿＞◡❛）▄︻▇▇〓　ティロ・フィナーレ！", tags: [""] },
      { symbol: "(๑•̀ω•́)ノ", tags: [""] },
      { symbol: "(΄◞ิ౪◟ิ‵)", tags: [""] },
      { symbol: "(┐「ε:)_三┌(.ω.)┐三_(:3 」∠)_", tags: [""] },
      { symbol: "ಥ_ಥ", tags: [""] },
      { symbol: "ಠ౪ಠ", tags: [""] },
      { symbol: "✧٩(ˊωˋ*)و✧", tags: [""] },
      { symbol: "‹‹\( ˙▿˙　)/››‹‹\(　˙▿˙ )/››", tags: [""] },
      { symbol: "₍₍ ◝('ω'◝) ⁾⁾ ₍₍ (◟'ω')◟ ⁾⁾", tags: [""] },
      { symbol: "ლ（╹ε╹ლ）", tags: [""] },
      { symbol: "ヾ(⌒(ﾉｼ'ω')ﾉｼ", tags: [""] },
      { symbol: "(☝ ՞ਊ ՞）☝", tags: [""] },
      { symbol: "( ε:)⌒ﾞ(.ω.)⌒ﾞ(:3 )", tags: [""] },
      { symbol: "( ΄◞ิ .̫.̫ ◟ิ‵)", tags: [""] },
      { symbol: "( ͡o ͜ʖ ͡o)", tags: [""] },
      { symbol: "(๑╹◡╹๑)", tags: [""] },
      { symbol: "(͡ ͡° ͜ つ ͡͡°)", tags: [""] },
      { symbol: "∠( ᐛ 」∠)_", tags: [""] },
      { symbol: "ᕙ(˵ ಠ ਊ ಠ ˵)ᕗ", tags: [""] },
      { symbol: "⎝(◕u◕)⎠", tags: [""] },
      { symbol: "⎝( OωO)⎠", tags: [""] },
      { symbol: "‹‹\(´ω` )/››‹‹\( 　´)/››‹‹\( ´ω`)/››", tags: [""] },
      { symbol: "(*°ω°*ฅ)*", tags: [""] },
      { symbol: "(╯✧∇✧)╯", tags: [""] },
      { symbol: "⸜(* ॑꒳ ॑* )⸝", tags: [""] },
      { symbol: "⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄", tags: [""] },
      { symbol: "ｽﾞｲ₍₍ (ง ˘ω˘ )ว ⁾⁾ ⁽⁽ 〪ɾ( ˘ω˘ 〫ɩ ) ₎₎ｽﾞｲ", tags: [""] },
    ],
  },
  無奈: {
    categoryTags: ["無奈"],
    items: [
      { symbol: "(´ー`)", tags: [""] },
      { symbol: "(‘⊙д-)", tags: [""] },
      { symbol: "(´c_`)", tags: [""] },
      { symbol: "(=m=)", tags: [""] },
      { symbol: "(´・Å・`)", tags: [""] },
      { symbol: "(´,_ゝ`)", tags: [""] },
      { symbol: "(´_ゝ`)", tags: [""] },
      { symbol: "(|||ﾟдﾟ)", tags: [""] },
      { symbol: "-`д´-", tags: [""] },
      { symbol: "╮(╯_╰)╭", tags: [""] },
      { symbol: "_(┐「ε:)_", tags: [""] },
      { symbol: "＿ﾉ乙(､ﾝ､)＿", tags: [""] },
      { symbol: "(´-ι_-｀)", tags: [""] },
      { symbol: "(´･_･`)", tags: [""] },
      { symbol: "|柱|ω・`)", tags: [""] },
      { symbol: "(ﾟ⊿ﾟ)", tags: [""] },
      { symbol: "(ㆆᴗㆆ)", tags: [""] },
      { symbol: "(　◜◡‾)", tags: [""] },
      { symbol: "┐(´д`)┌", tags: [""] },
      { symbol: "（’へ’）", tags: [""] },
      { symbol: "(´σ-`)", tags: [""] },
      { symbol: "(´～`)", tags: [""] },
      { symbol: "( ˘•ω•˘ )", tags: [""] },
      { symbol: "(눈‸눈)", tags: [""] },
      { symbol: "ʅ（´◔౪◔）ʃ", tags: [""] },
      { symbol: "ლ(◉◞౪◟◉ )ლ", tags: [""] },
      { symbol: "｡ﾟ(ﾟ´ω`ﾟ)ﾟ｡", tags: [""] },
      { symbol: "ლ(´•д• ̀ლ", tags: [""] },
      { symbol: "╮(′～‵〞)╭", tags: [""] },
      { symbol: "ლ(╯⊙ε⊙ლ╰)", tags: [""] },
      { symbol: "(´-ω-｀)", tags: [""] },
      { symbol: "( ´ﾟДﾟ`)", tags: [""] },
      { symbol: "┳━┳ノ( ' - 'ノ)", tags: [""] },
      { symbol: "┳━┳ノ( OωOノ)", tags: [""] },
      { symbol: "(≖＿≖)✧", tags: [""] },
      { symbol: "ƪ(•̃͡ε•̃͡)∫", tags: [""] },
      { symbol: "(｡-_-｡)", tags: [""] },
      { symbol: "( ¯•ω•¯ )", tags: [""] },
      { symbol: "╮(╯∀╰)╭", tags: [""] },
      { symbol: "( •́ _ •̀)？", tags: [""] },
      { symbol: "-//(ǒ.ǒ)//-", tags: [""] },
      { symbol: "_:(´□`」 ∠):_", tags: [""] },
      { symbol: "눈言눈", tags: [""] },
      { symbol: "(ㆀ˘･з･˘)", tags: [""] },
      { symbol: "(ノ〠_〠)", tags: [""] },
      { symbol: "¯\_(ツ)_/¯", tags: [""] },
      { symbol: "ㅍ_ㅍ", tags: [""] },
    ],
  },
  互動: {
    categoryTags: ["互動"],
    items: [
      { symbol: "(*´Д`)つ))´∀`)", tags: [""] },
      { symbol: "(o´・ω・`)σ)Д`)", tags: [""] },
      { symbol: "(*´ω`)人(´ω`*)", tags: [""] },
      { symbol: "(ｏﾟﾛﾟ)┌┛Σ(ﾉ´*ω*`)ﾉ", tags: [""] },
      { symbol: "(´>∀)人(´・ω・)ﾉヽ(・ε・*)人(-д-`)", tags: [""] },
      { symbol: "ヽ(∀ﾟ )人(ﾟ∀ﾟ)人( ﾟ∀)人(∀ﾟ )人(ﾟ∀ﾟ)人( ﾟ∀)ﾉ", tags: [""] },
      { symbol: "ლ(・´ｪ`・ლ)", tags: [""] },
      { symbol: "(σ回ω・)σ←↑→↓←↑", tags: [""] },
      { symbol: "(#‵)3′)▂▂▂▃▄▅～～～嗡嗡嗡嗡嗡", tags: [""] },
      { symbol: "#ﾟÅﾟ）⊂彡☆))ﾟДﾟ)･∵", tags: [""] },
      { symbol: "｡･ﾟ･(ﾉД`)ヽ(ﾟДﾟ )秀秀", tags: [""] },
      { symbol: "(ㄏ￣▽￣)ㄏ   ㄟ(￣▽￣ㄟ)", tags: [""] },
      { symbol: "ლ(ﾟдﾟლ)", tags: [""] },
      { symbol: "( ﾟ∀ﾟ)o彡ﾟ", tags: [""] },
      { symbol: "( ‘д‘⊂彡☆))Д´)", tags: [""] },
      { symbol: "(　′∀`)σ≡σ☆))Д′)", tags: [""] },
      { symbol: "ﾚ(ﾟ∀ﾟ;)ﾍ=З=З=З", tags: [""] },
      { symbol: "ε≡(ノ´＿ゝ｀）ノ", tags: [""] },
      { symbol: "魔貫光殺砲(ﾟДﾟ)σ━00000000000━●", tags: [""] },
      { symbol: "どこ━━━━(゜∀゜三゜∀゜)━━━━!!??", tags: [""] },
      { symbol: "σ(´∀｀*)", tags: [""] },
      { symbol: "┏( .-. ┏ ) ┓", tags: [""] },
      { symbol: "(∩^o^)⊃━☆ﾟ.*･｡", tags: [""] },
      { symbol: "..._〆(°▽°*)", tags: [""] },
      { symbol: "ε=ε=ヾ(;ﾟдﾟ)/", tags: [""] },
      { symbol: "ε≡ﾍ( ´∀`)ﾉ", tags: [""] },
      { symbol: "|Д`)ノ⌒●～*", tags: [""] },
      { symbol: "( ´∀`);y=ｰ(ﾟдﾟ)･∵. ﾀｰﾝ", tags: [""] },
      { symbol: "(´･д･｀)ﾊ(･д･｀*)", tags: [""] },
      { symbol: "(๑•̀ㅂ•́)و✧", tags: [""] },
      { symbol: "(“￣▽￣)-o█ █o-(￣▽￣”)/", tags: [""] },
      { symbol: "(´;ω;`)ヾ(･∀･`)", tags: [""] },
      { symbol: "(・∀・)ノ三G[__]ｺ", tags: [""] },
      { symbol: "(｢･ω･)｢", tags: [""] },
      { symbol: "=└(┐卍^o^)卍", tags: [""] },
      { symbol: "(=ﾟДﾟ=) ▄︻┻┳━ ·.`.`.`.", tags: [""] },
      { symbol: "( ´-ω ･)▄︻┻┳══━", tags: [""] },
      { symbol: "(:3っ)へ ヽ(´Д｀●ヽ)", tags: [""] },
      { symbol: ": ♡｡ﾟ.(*♡´◡` 人´◡` ♡*)ﾟ♡ °・", tags: [""] },
      { symbol: "( ´･･)ﾉ(._.`)", tags: [""] },
      { symbol: "(´д((☆ミPia!⊂▼(ｏ ‵－′ｏ)▼つPia!彡★))∀`)", tags: [""] },
      { symbol: "(￣ε(#￣)☆", tags: [""] },
      { symbol: "(/ ↀ3ↀ)/q(﹌ω﹌ )", tags: [""] },
      { symbol: "╮/(＞▽<)人(>▽＜)╭", tags: [""] },
      { symbol: "(〃￣ω￣)人(￣︶￣〃)", tags: [""] },
      { symbol: "┬─┬ ノ( ' - 'ノ)", tags: [""] },
      { symbol: "（つ> _◕）つ︻╦̵̵͇̿̿̿̿╤───", tags: [""] },
      { symbol: "༼ つ/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿◕ _◕ ༽つ/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿", tags: [""] },
      { symbol: "( ￣□￣)/ 敬禮!! <(￣ㄧ￣ ) <(￣ㄧ￣ )", tags: [""] },
      { symbol: "ヽ(゜▽゜　)－C<(/;◇;)/~[拖走]", tags: [""] },
      { symbol: "~(～o￣▽￣)～o.....o～(＿△＿o～)~..", tags: [""] },
      { symbol: "๛ก(ｰ̀ωｰ́ก)", tags: [""] },
      { symbol: "Σ Σ Σ (」○ ω○ )／", tags: [""] },
      { symbol: "龜派氣功(ﾟДﾟ)< ============O))", tags: [""] },
      { symbol: "＼(・ω・＼)SAN値！(／・ω・)／ピンチ！", tags: [""] },
      { symbol: "(」・ω・)」SAN値！(／・ω・)／ピンチ！", tags: [""] },
      { symbol: "(╭☞•́⍛•̀)╭☞", tags: [""] },
      { symbol: "(シ_ _)シ", tags: [""] },
      { symbol: "─=≡Σ(((っﾟДﾟ)っ", tags: [""] },
      { symbol: "─=≡Σ((( つ•̀ω•́)=c＜一ω<))", tags: [""] },
      { symbol: "༼ つ ◕_◕ ༽つ", tags: [""] },
      { symbol: "( ￣□￣)σ 論破!! ︴≡║██言彈██》", tags: [""] },
      { symbol: "ヽ(゜▽゜ )－C<(/;◇;)/~", tags: [""] },
      { symbol: "༼ つ◕_◕ ༽つ", tags: [""] },
      { symbol: "●｀ε´●)爻(●｀ε´● )", tags: [""] },
      { symbol: "٩(•ิ˓̭ •ิ )ง", tags: [""] },
      { symbol: "ﾚ(ﾟ∀ﾟ;)ﾍ　ﾍ( ﾟ∀ﾟ;)ﾉ", tags: [""] },
      { symbol: "(つ´ω`)つ", tags: [""] },
      { symbol: "((꜆꜄꜆ ˙꒳˙)꜆꜄꜆ｵﾗｵﾗｵﾗｵﾗ", tags: [""] },
      { symbol: "̿̿ ̿̿ ̿̿ ̿'̿’\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/‘̿̿ ̿ ̿ ̿ ̿ ̿", tags: [""] },
    ],
  },
  沮喪: {
    categoryTags: ["沮喪"],
    items: [
      { symbol: "( ´･ω)", tags: [""] },
      { symbol: "(｡í _ ì｡)", tags: [""] },
      { symbol: "ヾ(⌒(_´･ㅅ･`)_", tags: [""] },
      { symbol: "(｡ŏ_ŏ)", tags: [""] },
      { symbol: "(◞‸◟)", tags: [""] },
      { symbol: "il||li _|￣|○ヽ(･ω･｀)", tags: [""] },
      { symbol: "-//(ǒ.ǒ)//-", tags: [""] },
      { symbol: "¯\_(ツ)_/¯", tags: [""] },
    ],
  },
  道歉: {
    categoryTags: ["道歉"],
    items: [
      { symbol: "<(_ _)>", tags: [""] },
      { symbol: "m(｡≧ｴ≦｡)m", tags: [""] },
      { symbol: "(●б人<●)", tags: [""] },
      { symbol: "(；´ﾟωﾟ｀人)", tags: [""] },
      { symbol: "๛ก（ーωーก）", tags: [""] },
      { symbol: "＞ᨓ＜", tags: [""] },
    ],
  },
  喜歡: {
    categoryTags: ["喜歡", "愛"],
    items: [
      { symbol: "(*´∀`)~♥", tags: [""] },
      { symbol: "ε٩(๑> ₃ <)۶з", tags: [""] },
      { symbol: "(　ﾟ∀ﾟ)つ≡≡≡♡♡♡)`ν゜)ｸﾞｼｬ", tags: [""] },
      { symbol: '(´▽`ʃ♡ƪ)"', tags: [""] },
      { symbol: "(｡ŏ_ŏ)", tags: [""] },
      { symbol: "(●´ω｀●)ゞ", tags: [""] },
      { symbol: "♡(*´∀｀*)人(*´∀｀*)♡", tags: [""] },
      { symbol: "(*´з｀*)", tags: [""] },
      { symbol: "ヾ(●゜▽゜●)♡", tags: [""] },
      { symbol: "( శ 3ੜ)～♥", tags: [""] },
      { symbol: "( ♥д♥)", tags: [""] },
      { symbol: "(♡˙︶˙♡)", tags: [""] },
      { symbol: "Σ>―(〃°ω°〃)♡→", tags: [""] },
      { symbol: "(´,,•ω•,,)♡", tags: [""] },
      { symbol: "( *¯ ³¯*)♡ㄘゅ", tags: [""] },
      { symbol: "(　ﾟ∀ﾟ) ﾉ♡", tags: [""] },
      { symbol: "(*´д`)~♥", tags: [""] },
      { symbol: "(╭￣3￣)╭♡", tags: [""] },
      { symbol: "(,,Ծ 3 Ծ,,)", tags: [""] },
    ],
  },
  動物: {
    categoryTags: ["動物"],
    items: [
      { symbol: "(￣(エ)￣)", tags: [""] },
      { symbol: "(●｀･(ｴ)･´●)", tags: [""] },
      { symbol: "┏((＝￣(ｴ)￣=))┛", tags: [""] },
      { symbol: "(ó㉨ò)", tags: [""] },
      { symbol: "<*)) >>=<", tags: [""] },
      { symbol: "≧〔゜゜〕≦", tags: [""] },
      { symbol: "( ´(00)`)", tags: [""] },
      { symbol: "ヾ(；ﾟ(OO)ﾟ)ﾉ", tags: [""] },
      { symbol: "(❍ᴥ❍ʋ)", tags: [""] },
      { symbol: "／/( ◕‿‿◕ )＼", tags: [""] },
      { symbol: "(•ө•)", tags: [""] },
      { symbol: "( ఠൠఠ )ﾉ", tags: [""] },
      { symbol: "(◔⊖◔)つ", tags: [""] },
      { symbol: "(o･e･)", tags: [""] },
      { symbol: "( ิ◕㉨◕ ิ)", tags: [""] },
      { symbol: "(ΦωΦ)", tags: [""] },
      { symbol: "(｡･㉨･｡)", tags: [""] },
      { symbol: "ก็ʕ•͡ᴥ•ʔ ก้", tags: [""] },
      { symbol: "( ﾟ Χ ﾟ)", tags: [""] },
      { symbol: "(⁰⊖⁰)", tags: [""] },
      { symbol: "(( へ(へ´∀`)へ", tags: [""] },
      { symbol: "(=´ω`=)", tags: [""] },
      { symbol: "ヽ(=^･ω･^=)丿", tags: [""] },
      { symbol: "( Φ ω Φ )", tags: [""] },
      { symbol: "ヾ(*ΦωΦ)ツ", tags: [""] },
      { symbol: "(:◎)≡", tags: [""] },
      { symbol: "(´;;◉;⊖;◉;;｀)", tags: [""] },
      { symbol: "(=´ᴥ`)", tags: [""] },
      { symbol: "Φ౪Φ", tags: [""] },
      { symbol: "ฅ●ω●ฅ", tags: [""] },
      { symbol: "(･8･)", tags: [""] },
      { symbol: "(=^-ω-^=)", tags: [""] },
      { symbol: "( ˊ̱˂˃ˋ̱ )", tags: [""] },
      { symbol: "⧸⎩⎠⎞͏(・∀・)⎛͏⎝⎭⧹", tags: [""] },
      { symbol: "Ꮚ･ꈊ･Ꮚ", tags: [""] },
      { symbol: "ฅ^•ﻌ•^ฅ", tags: [""] },
      { symbol: "/ᐠ｡ꞈ｡ᐟ\\", tags: [""] },
      { symbol: "/ᐠ .ᆺ. ᐟ\ﾉ", tags: [""] },
      { symbol: "▼・ᴥ・▼", tags: [""] },
      { symbol: "⋛⋋( ‘Θ’)⋌⋚", tags: [""] },
      { symbol: ">ㅅ<", tags: [""] },
    ],
  },
  驚訝: {
    categoryTags: ["驚訝"],
    items: [
      { symbol: "(д) ﾟﾟ", tags: [""] },
      { symbol: "Σ(;ﾟдﾟ)", tags: [""] },
      { symbol: "(●▼●;)", tags: [""] },
      { symbol: "┌|◎o◎|┘", tags: [""] },
      { symbol: "(｡•ㅅ•｡)♡", tags: [""] },
      { symbol: "∑(ι´Дン)ノ", tags: [""] },
      { symbol: "(°ﾛ°٥)", tags: [""] },
      { symbol: "ฅ(๑*д*๑)ฅ!!", tags: [""] },
      { symbol: "＼(●o○;)ノ", tags: [""] },
      { symbol: "Σ(°Д°;", tags: [""] },
      { symbol: "Σヽ(ﾟД ﾟ; )ﾉ", tags: [""] },
      { symbol: "∑(￣□￣;)", tags: [""] },
      { symbol: "∑(✘Д✘๑ )", tags: [""] },
      { symbol: "ㅇㅅㅇ", tags: [""] },
      { symbol: "(;◉∀◉)オッ(∀◉)◉ハッ(;∀)◉◉ヨｫー!!!", tags: [""] },
      { symbol: "( ºωº )", tags: [""] },
      { symbol: "δ△δ", tags: [""] },
    ],
  },
};
