// 型別定義
export type PrefixType = "repeat" | "format" | "order";

export interface PrefixSymbol {
  symbol: string;
  name: string;
  type: PrefixType;
  editable: boolean;
  format?: string;
  order?: string[];
}

export const prefixSymbols: PrefixSymbol[] = [
  { symbol: " ", name: "半形空格", type: "repeat", editable: false },
  { symbol: "　", name: "全形空格", type: "repeat", editable: false },
  { symbol: "- ", name: "短橫線", type: "repeat", editable: false },
  { symbol: "• ", name: "圓點", type: "repeat", editable: false },
  {
    symbol: "1. ",
    name: "數字列表",
    type: "format",
    format: "n. ",
    editable: false,
  },
  {
    symbol: "01. ",
    name: "二位數字列表",
    type: "format",
    format: "nn. ",
    editable: false,
  },
  {
    symbol: "①",
    name: "圓圈數字",
    type: "order",
    order: [
      "① ",
      "② ",
      "③ ",
      "④ ",
      "⑤ ",
      "⑥ ",
      "⑦ ",
      "⑧ ",
      "⑨ ",
      "⑩ ",
      "⑪ ",
      "⑫ ",
      "⑬ ",
      "⑭ ",
      "⑮ ",
      "⑯ ",
      "⑰ ",
      "⑱ ",
      "⑲ ",
      "⑳ ",
    ],
    editable: false,
  },
  {
    symbol: "➊ ",
    name: "黑色圓圈數字",
    type: "order",
    order: ["➊ ", "➋ ", "➌ ", "➍ ", "➎ ", "➏ ", "➐ ", "➑ ", "➒ ", "➓ "],
    editable: false,
  },
  {
    symbol: "㊀ ",
    name: "圓圈中文數字",
    type: "order",
    order: [
      "㊀ ",
      "㊁ ",
      "㊂ ",
      "㊃ ",
      "㊄ ",
      "㊅ ",
      "㊆ ",
      "㊇ ",
      "㊈ ",
      "㊉ ",
    ],
    editable: false,
  },
  {
    symbol: "⑴ ",
    name: "括號數字",
    type: "order",
    order: [
      "⑴ ",
      "⑵ ",
      "⑶ ",
      "⑷ ",
      "⑸ ",
      "⑹ ",
      "⑺ ",
      "⑻ ",
      "⑼ ",
      "⑽ ",
      "⑾ ",
      "⑿ ",
    ],
    editable: false,
  },
  {
    symbol: "㈠ ",
    name: "括號中文數字",
    type: "order",
    order: [
      "㈠ ",
      "㈡ ",
      "㈢ ",
      "㈣ ",
      "㈤ ",
      "㈥ ",
      "㈦ ",
      "㈧ ",
      "㈨ ",
      "㈩ ",
    ],
    editable: false,
  },
  {
    symbol: "a. ",
    name: "英文列表",
    type: "order",
    order: [
      "a. ",
      "b. ",
      "c. ",
      "d. ",
      "e. ",
      "f. ",
      "g. ",
      "h. ",
      "i. ",
      "j. ",
      "k. ",
      "l. ",
      "m. ",
      "n. ",
      "o. ",
      "p. ",
      "q. ",
      "r. ",
      "s. ",
      "t. ",
      "u. ",
      "v. ",
      "w. ",
      "x. ",
      "y. ",
      "z. ",
    ],
    editable: false,
  },
  {
    symbol: "A. ",
    name: "大寫英文列表",
    type: "order",
    order: [
      "A. ",
      "B. ",
      "C. ",
      "D. ",
      "E. ",
      "F. ",
      "G. ",
      "H. ",
      "I. ",
      "J. ",
      "K. ",
      "L. ",
      "M. ",
      "N. ",
      "O. ",
      "P. ",
      "Q. ",
      "R. ",
      "S. ",
      "T. ",
      "U. ",
      "V. ",
      "W. ",
      "X. ",
      "Y. ",
      "Z. ",
    ],
    editable: false,
  },
  {
    symbol: "(a) ",
    name: "英文括號列表",
    type: "order",
    order: [
      "(a) ",
      "(b) ",
      "(c) ",
      "(d) ",
      "(e) ",
      "(f) ",
      "(g) ",
      "(h) ",
      "(i) ",
      "(j) ",
      "(k) ",
      "(l) ",
      "(m) ",
      "(n) ",
      "(o) ",
      "(p) ",
      "(q) ",
      "(r) ",
      "(s) ",
      "(t) ",
      "(u) ",
      "(v) ",
      "(w) ",
      "(x) ",
      "(y) ",
      "(z) ",
    ],
    editable: false,
  },

  {
    symbol: "一、",
    name: "中文數字列表",
    type: "order",
    order: [
      "一、",
      "二、",
      "三、",
      "四、",
      "五、",
      "六、",
      "七、",
      "八、",
      "九、",
      "十、",
      "十一、",
      "十二、",
      "十三、",
      "十四、",
      "十五、",
      "十六、",
      "十七、",
      "十八、",
      "十九、",
      "二十、",
      "二十一、",
      "二十二、",
      "二十三、",
      "二十四、",
      "二十五、",
      "二十六、",
      "二十七、",
      "二十八、",
      "二十九、",
      "三十、",
    ],
    editable: false,
  },
  {
    symbol: "甲、",
    name: "甲乙丙",
    type: "order",
    order: [
      "甲、",
      "乙、",
      "丙、",
      "丁、",
      "戊、",
      "己、",
      "庚、",
      "辛、",
      "壬、",
      "癸、",
      "申、",
      "酉、",
      "戌、",
      "亥、",
    ],
    editable: false,
  },
];
